version: 2
jobs:
  testcafe:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/repo/testcafe
    steps:
      - checkout:
          path: ~/repo
      - run: npm it

workflows:
  version: 2
  test:
    jobs:
      - testcafe
